efficientnet_v2:
  data:
    batch_size: 64

  training:
    lr: 0.001
    epochs: 18
    weight_decay: .0001
    warmup_steps: 256 # num warmup epochs * batch size, as its stepped per batch
    cosine_annealing:
      T_0: 14 # number of epochs it takes from max to min lr; inside batch loop lr is calculated using batch indexes
      eta_min: .0001

densenet: # apparantly needs more epochs than efficientnet v2
  data:
    batch_size: 64

  training:
    lr: 0.0005
    epochs: 30
    weight_decay: .0001
    warmup_steps: 384 # num warmup epochs * batch size, as its stepped per batch
    cosine_annealing:
      T_0: 24
      eta_min: .00005

convnext: # often uses a cosine decay schedule
  data:
    batch_size: 64

  training:
    lr: 0.001
    epochs: 30
    weight_decay: .05
    warmup_steps: 384 # num warmup epochs * batch size, as its stepped per batch
    cosine_annealing:
      T_0: 24
      eta_min: .0001
